development:
  adapter: mysql2
  database: openneo_id
  encoding: utf8
  username: openneo_id
  password: fVRCCwLC
  host: localhost

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
