server:
  development:
    apps:
      impress: Dress to Impress
      newimpress: Dress to Impress (beta)
      impress.dev: Dress to Impress (dev)
    
    apps_without_passthru:
      - impress
      - betaimpress
    
    id: openneo
    
    secret: zaheh2draswAb8eneca$3an?2ADAsTuwra8h7BujUBr_w--p2-a@e?u!taQux3tr
