server:
  development:
    apps:
      impress: Dress to Impress
      impress.dev: Dress to Impress (dev server)
      oldimpress: Dress to Impress (old, boring backup server)
    
    apps_without_passthru:
      - oldimpress
    
    id: openneo
    
    secret: zaheh2draswAb8eneca$3an?2ADAsTuwra8h7BujUBr_w--p2-a@e?u!taQux3tr
  
  production:
    apps:
      impress: Dress to Impress
      oldimpress: Dress to Impress (old, boring backup server)
    
    apps_without_passthru:
      - oldimpress
    
    id: openneo
    
    secret: dlAGOaqLa*oe#+e6rou0woaph3a&i14ouml!B5@clew@2swoan-ejia?L!tIu&!u
